// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz51-Y8r_ucFYtANtHtMIeZbwK3XQhZ-g',
    appId: '1:434616782505:web:4032fc6bec6d914e0463b8',
    messagingSenderId: '434616782505',
    projectId: 'flutter-test-a9459',
    authDomain: 'flutter-test-a9459.firebaseapp.com',
    storageBucket: 'flutter-test-a9459.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFU39woygIxIzS-s-ZIX2ztxpSjMl_Yiw',
    appId: '1:434616782505:android:bce63eaec7f627a90463b8',
    messagingSenderId: '434616782505',
    projectId: 'flutter-test-a9459',
    storageBucket: 'flutter-test-a9459.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYpoof1rwtzIwY1FNrYCDjeaKpgAtFytY',
    appId: '1:434616782505:ios:ca3120b7c54eb1810463b8',
    messagingSenderId: '434616782505',
    projectId: 'flutter-test-a9459',
    storageBucket: 'flutter-test-a9459.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYpoof1rwtzIwY1FNrYCDjeaKpgAtFytY',
    appId: '1:434616782505:ios:ca3120b7c54eb1810463b8',
    messagingSenderId: '434616782505',
    projectId: 'flutter-test-a9459',
    storageBucket: 'flutter-test-a9459.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz51-Y8r_ucFYtANtHtMIeZbwK3XQhZ-g',
    appId: '1:434616782505:web:eddbd5eee6a7f3950463b8',
    messagingSenderId: '434616782505',
    projectId: 'flutter-test-a9459',
    authDomain: 'flutter-test-a9459.firebaseapp.com',
    storageBucket: 'flutter-test-a9459.firebasestorage.app',
  );
}
